### ISSUE TITLE
"Method code too large!" exception is thrown when routes file is large

### ISSUE THREAD

**Issue by emac** [sbt/sbt-jacoco#101]
### Expected vs Actual Behaviour

My project uses Play framework and contains a large `routes` file, more than 1000 lines. When I run `sbt jacoco` command in command line, it throws "Method code too large!" exception (see below). The reason is that Play framework automatically generates a bunch of classes from `routes` file, and one class contains a large method that violates JVM's limitation that methods cannot be larger than 64k (65536 bytes).

One solution I think is to add a new config to allow user to exclude classes from instrument.

```
java.io.IOException: Error while instrumenting class Routes$$anonfun$routes$1.class.
	at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:166)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:117)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4$$anonfun$apply$3.apply(InstrumentationUtils.scala:64)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4$$anonfun$apply$3.apply(InstrumentationUtils.scala:61)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
	at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	at scala.util.control.Exception$Catch.either(Exception.scala:124)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:53)
	at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:50)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4.apply(InstrumentationUtils.scala:61)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4.apply(InstrumentationUtils.scala:60)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at com.github.sbt.jacoco.data.InstrumentationUtils$.instrumentClasses(InstrumentationUtils.scala:60)
	at com.github.sbt.jacoco.BaseJacocoPlugin$$anonfun$taskValues$8.apply(BaseJacocoPlugin.scala:98)
	at com.github.sbt.jacoco.BaseJacocoPlugin$$anonfun$taskValues$8.apply(BaseJacocoPlugin.scala:98)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.getSize(MethodWriter.java:2079)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:838)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:91)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:114)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4$$anonfun$apply$3.apply(InstrumentationUtils.scala:64)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4$$anonfun$apply$3.apply(InstrumentationUtils.scala:61)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
	at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	at scala.util.control.Exception$Catch.either(Exception.scala:124)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
	at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)
	at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:53)
	at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:50)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4.apply(InstrumentationUtils.scala:61)
	at com.github.sbt.jacoco.data.InstrumentationUtils$$anonfun$instrumentClasses$4.apply(InstrumentationUtils.scala:60)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at com.github.sbt.jacoco.data.InstrumentationUtils$.instrumentClasses(InstrumentationUtils.scala:60)
	at com.github.sbt.jacoco.BaseJacocoPlugin$$anonfun$taskValues$8.apply(BaseJacocoPlugin.scala:98)
	at com.github.sbt.jacoco.BaseJacocoPlugin$$anonfun$taskValues$8.apply(BaseJacocoPlugin.scala:98)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (admin/test:fullClasspath) java.io.IOException: Error while instrumenting class Routes$$anonfun$routes$1.class.
```

### Steps to Reproduce

```
> sbt jacoco
```

### Environment

* SBT version: 0.13.16
* Plugin version: 3.0.3
* Scala version(s): 2.11.11
* Java version: 1.8.60

**Comment by KoenDG** [comment]
Also affected by this issue, using Play 2.6.6 and scala 2.12.3.

Using Play 2.6.5 and scala 2.11.11, everything works fine, all code and routes file is identical.

Both times, plugin version 3.0.2

**Comment by ca7erina** [comment]
Is there any working solution for this "method too large" problem? how can I exclude the file from instrumentation so far? I see this PR still open, is there any workaround? my problem is the "Route.class" is huge

**Comment by tachucj** [comment]
> Is there any working solution for this "method too large" problem? how can I exclude the file from instrumentation so far? I see this PR still open, is there any workaround? my problem is the "Route.class" is huge

When I faced this I had to split routes file. No other solutions for me.

**Comment by mgor** [comment]
Since it's a "hard" limit in the JVM, you'd have to make sure that you instrumented code fits within the size limit, hence as @tachucj says; split up the big classes and/or methods.
