### ISSUE TITLE
enablePlugins(JacocoItPlugin) resulsts in Runtime references to undefined settings

### ISSUE THREAD

**Issue by karthikkbaalaji** [sbt/sbt-jacoco#103]
### Expected vs Actual Behaviour

It should...
run the IT test when I enable JacocoItPlugin

Instead it...
Runtime references to undefined settings: 
example/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)

### Steps to Reproduce
I have the following project settings

example-play-app
|--main
|----build.sbt
|--modules
|----build.sbt
|--example
|----build.sbt
|--build.sbt

In the root build.sbt I have,
```scala
lazy val `root` = (project in file("."))
  .settings(commonSettings: _*)
  .enablePlugins(PlayJava, PlayEbean, JacocoItPlugin)
  .aggregate(common, main, example)
  .dependsOn(common, main, example)

lazy val common = (project in file("./common"))
  .settings(commonSettings)
  .enablePlugins(PlayJava)
lazy val main = (project in file("./main"))
  .settings(commonSettings)
  .enablePlugins(PlayJava)
  .dependsOn(common % "compile->compile")
lazy val example = (project in file("./modules/example"))
  .settings(commonSettings)
  .enablePlugins(PlayJava)

```
When I run sbt it:jacoco I get the following error:

```
[error] Runtime references to undefined settings: 
[error] 
[error]   example/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   main/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   common/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error]  
[error] 	at sbt.internal.util.Init.Uninitialized(Settings.scala:360)
[error] 	at sbt.internal.util.Init.Uninitialized$(Settings.scala:347)
[error] 	at sbt.Def$.Uninitialized(Def.scala:13)
[error] 	at sbt.internal.util.Init.make(Settings.scala:208)
[error] 	at sbt.internal.util.Init.make$(Settings.scala:197)
[error] 	at sbt.Def$.make(Def.scala:13)
[error] 	at sbt.internal.Load$.$anonfun$apply$5(Load.scala:264)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:259)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Runtime references to undefined settings: 
[error] 
[error]   example/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   main/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   common/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error]  
[error] Use 'last' for the full log.
```

### Environment

* SBT version: 1.0.2
* Plugin version: 3.0.3
* Scala version(s): 2.11.11
* Java version: 1.8

**Comment by karthikkbaalaji** [comment]
@stringbean could you take look at this issue?

**Comment by stringbean** [comment]
Sorry for the delay in replying.

Have you tried adding `JacocoItPlugin` to the `enablePlugins` for `common`, `example` and `main`?

**Comment by karthikkbaalaji** [comment]
@stringbean same error even with enable plugins for common, example and main

```
lazy val common = (project in file("./common")).settings(commonSettings).enablePlugins(PlayJava, JacocoItPlugin)
lazy val main = (project in file("./main")).settings(commonSettings).enablePlugins(PlayJava, JacocoItPlugin).dependsOn(common % "compile->compile")
lazy val example = (project in file("./modules/example")).settings(commonSettings).enablePlugins(PlayJava, JacocoItPlugin)
```
Error:
```
[error] Runtime references to undefined settings: 
[error] 
[error]   example/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   main/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   common/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error]  
[error] 	at sbt.internal.util.Init.Uninitialized(Settings.scala:360)
[error] 	at sbt.internal.util.Init.Uninitialized$(Settings.scala:347)
[error] 	at sbt.Def$.Uninitialized(Def.scala:13)
[error] 	at sbt.internal.util.Init.make(Settings.scala:208)
[error] 	at sbt.internal.util.Init.make$(Settings.scala:197)
[error] 	at sbt.Def$.make(Def.scala:13)
[error] 	at sbt.internal.Load$.$anonfun$apply$5(Load.scala:264)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:259)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Runtime references to undefined settings: 
[error] 
[error]   example/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   main/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error] 
[error]   common/it:jacoco from root/it:jacocoAggregate (BaseJacocoPlugin.scala:73)
[error]  
```

**Comment by karthikkbaalaji** [comment]
@stringbean it worked after adding **.configs( IntegrationTest )** to each root, common, main, example. 

Thanks for looking into it, but this needs to be documented.
