### ISSUE TITLE
XML/CSV report format causing FileNotFoundException

### ISSUE THREAD

**Issue by Z1kkurat** [sbt/sbt-jacoco#89]
Problem appears on Windows.

When XML or CSV report is going first in list of formats, reporting fails with `FileNotFoundException`:
```java
[error] java.io.FileNotFoundException: C:\dev\projects\scala\sandbox\module1\target\scala-2.12\jacoco\report\jacoco.xml (The system cannot find the file specified)
[error]         at java.io.FileOutputStream.open0(Native Method)
[error]         at java.io.FileOutputStream.open(FileOutputStream.java:270)
[error]         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[error]         at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[error]         at com.github.sbt.jacoco.report.formats.XMLReportFormat.createVisitor(XMLReportFormat.scala:24)
[error]         at com.github.sbt.jacoco.report.Report.createReport(Report.scala:130)
[error]         at com.github.sbt.jacoco.report.Report.$anonfun$generate$1(Report.scala:40)
[error]         at com.github.sbt.jacoco.report.Report.$anonfun$generate$1$adapted(Report.scala:40)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error]         at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error]         at com.github.sbt.jacoco.report.Report.generate(Report.scala:40)
[error]         at com.github.sbt.jacoco.report.ReportUtils$.generateReport(ReportUtils.scala:38)
[error]         at com.github.sbt.jacoco.BaseJacocoPlugin.$anonfun$taskValues$5(BaseJacocoPlugin.scala:81)
[error]         at com.github.sbt.jacoco.BaseJacocoPlugin.$anonfun$taskValues$5$adapted(BaseJacocoPlugin.scala:74)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (module1/test:jacocoReport) java.io.FileNotFoundException: C:\dev\projects\scala\sandbox\module1\target\scala-2.12\jacoco\report\jacoco.xml (The system cannot find the file specified)
[error] Total time: 6 s, completed 29.09.2017 21:06:49
```

But when ScalaHTML or HTML is going first in list, everything is OK.

### Steps to Reproduce
- Jacoco configuration:
```scala
lazy val jacoco = Seq(
  jacocoReportSettings in Test := JacocoReportSettings()
    .withFileEncoding("UTF-8")
    .withThresholds(JacocoThresholds(method = 90.0, line = 90.0))
    .withFormats(JacocoReportFormats.XML, JacocoReportFormats.CSV, JacocoReportFormats.HTML, JacocoReportFormats.ScalaHTML)
)
```
- Running
`sbt clean jacoco`

### Environment
* OS: Windows
* SBT version: 1.0.0
* Plugin version: 3.0.1
* Scala version(s): 2.12.3
* Java version: 1.8.0_131

**Comment by stringbean** [comment]
Fixed in 3.0.2
